spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.producer.acks=all
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB
server.tomcat.max-swallow-size=20MB

aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket-name=${AWS_BUCKET_NAME}

